# Generated by Django 4.0.1 on 2022-02-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transactions_classespurchased_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
