# Generated by Django 4.0.1 on 2022-02-10 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_details', '0002_classdetails_class_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classdetails',
            name='class_id',
        ),
    ]
