# Generated by Django 4.0.1 on 2022-02-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessClass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('class_type', models.CharField(choices=[('DM', 'Dominate'), ('KO', 'Kore'), ('LO', 'Leanout'), ('MD', 'Meltdown'), ('RM', 'Remixed')], default='DM', max_length=2)),
                ('date_time', models.DateTimeField()),
                ('instructor', models.CharField(choices=[('EM', 'Ernest'), ('ER', 'Eunice'), ('FG', 'Faith'), ('RK', 'Reagan'), ('SL', 'Samson')], default='EM', max_length=2)),
                ('spot_one_booked', models.BooleanField(default=False)),
                ('spot_two_booked', models.BooleanField(default=False)),
                ('spot_three_booked', models.BooleanField(default=False)),
            ],
        ),
    ]
