# Generated by Django 4.0.1 on 2022-02-07 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.CharField(default='', max_length=30)),
                ('class_instructor', models.CharField(default='', max_length=30)),
                ('date', models.DateField(default='')),
                ('time', models.TimeField(default='')),
                ('spot', models.CharField(default='', max_length=30)),
                ('user', models.ForeignKey(default='accounts.Account', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
