# Generated by Django 4.0.1 on 2022-02-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_class', '0002_alter_fitnessclass_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessclass',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
