# Generated by Django 4.0.1 on 2022-02-09 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_class', '0004_fitnessclass_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessclass',
            name='spot',
            field=models.IntegerField(default='', max_length=10),
        ),
    ]
