# Generated by Django 4.0.1 on 2022-02-09 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_class', '0006_alter_fitnessclass_spot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessclass',
            name='date',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='fitnessclass',
            name='time',
            field=models.CharField(default='', max_length=20),
        ),
    ]
