# Generated by Django 4.0.1 on 2022-02-08 05:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classesPurchased', models.IntegerField(default=0, max_length=20)),
                ('classesUsed', models.IntegerField(default=0, max_length=20)),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField(default='')),
                ('name', models.CharField(max_length=20)),
                ('user', models.ForeignKey(default='accounts.Account', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
