# Generated by Django 4.0.1 on 2022-02-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_transactions_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
