# Generated by Django 4.0.1 on 2022-02-08 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_review_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='time',
            field=models.TimeField(default=datetime.time),
        ),
    ]
