# Generated by Django 4.0.1 on 2022-02-09 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.CharField(default='', max_length=30)),
                ('date', models.CharField(default='', max_length=20)),
                ('time', models.CharField(default='', max_length=20)),
                ('class_instructor', models.CharField(default='', max_length=30)),
                ('spot_one_booked', models.BooleanField(default=False)),
                ('spot_two_booked', models.BooleanField(default=False)),
                ('spot_three_booked', models.BooleanField(default=False)),
                ('spot_four_booked', models.BooleanField(default=False)),
                ('spot_five_booked', models.BooleanField(default=False)),
                ('spot_six_booked', models.BooleanField(default=False)),
                ('spot_seven_booked', models.BooleanField(default=False)),
                ('spot_eight_booked', models.BooleanField(default=False)),
                ('spot_nine_booked', models.BooleanField(default=False)),
                ('spot_ten_booked', models.BooleanField(default=False)),
                ('spot_eleven_booked', models.BooleanField(default=False)),
                ('spot_twelve_booked', models.BooleanField(default=False)),
                ('spot_thirteen_booked', models.BooleanField(default=False)),
                ('spot_fourteen_booked', models.BooleanField(default=False)),
                ('spot_fifteen_booked', models.BooleanField(default=False)),
                ('spot_sixteen_booked', models.BooleanField(default=False)),
                ('spot_seventeen_booked', models.BooleanField(default=False)),
                ('spot_eighteen_booked', models.BooleanField(default=False)),
                ('spot_nineteen_booked', models.BooleanField(default=False)),
                ('spot_twenty_booked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default='accounts.Account', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
