# Generated by Django 4.0.1 on 2022-02-09 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classdetails',
            name='user',
        ),
    ]
