# Generated by Django 4.0.1 on 2022-02-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classdetails',
            name='class_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
