# Generated by Django 4.0.1 on 2022-02-10 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_details', '0002_remove_classdetails_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='classdetails',
            name='button_id',
            field=models.IntegerField(default=0),
        ),
    ]
