# Generated by Django 4.0.1 on 2022-02-10 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_details', '0003_classdetails_button_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classdetails',
            name='button_id',
            field=models.CharField(default='', max_length=10),
        ),
    ]
