# Generated by Django 4.0.1 on 2022-02-03 11:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contact', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(regex='[6,8,9]\\d\\d\\d\\d\\d\\d\\d')])),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('address_line', models.CharField(max_length=150)),
                ('postal_code', models.CharField(max_length=10)),
                ('emergency_contact', models.CharField(max_length=50)),
                ('emergency_number', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(regex='[6,8,9]\\d\\d\\d\\d\\d\\d\\d')])),
                ('user', models.ForeignKey(default='accounts.Account', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
