# Generated by Django 4.0.1 on 2022-02-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='unit',
            field=models.CharField(default='', max_length=10),
        ),
    ]
