# Generated by Django 4.0.1 on 2022-02-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_details', '0004_alter_personaldetails_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
    ]
