# Generated by Django 4.0.1 on 2022-02-04 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_details', '0005_alter_personaldetails_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetails',
            name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='emergency_number',
        ),
    ]
