# Generated by Django 4.0.1 on 2022-02-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_details', '0008_alter_personaldetails_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
