# Generated by Django 4.0.1 on 2022-02-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_details', '0003_alter_personaldetails_address_line_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
